# Generated by Django 3.0 on 2024-02-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0006_assignmentt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san', models.CharField(max_length=50)),
                ('ssubject', models.CharField(max_length=150)),
                ('scrted', models.DateField()),
                ('ssubd', models.DateField(null=True)),
                ('samarks', models.IntegerField(default=0)),
                ('sactive', models.CharField(choices=[('0', 'Start'), ('1', 'Activated'), ('2', 'Submitted'), ('3', 'Verified')], default='0', max_length=5)),
                ('sarev', models.CharField(max_length=150, null=True)),
                ('sastre', models.CharField(max_length=200, null=True)),
                ('asd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASMApp.AssignmentT')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
