# Generated by Django 3.0 on 2024-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0007_assignmentst'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentst',
            name='stactive',
            field=models.CharField(choices=[('4', 'Not Verified'), ('3', 'Verified')], default='4', max_length=3),
        ),
    ]
