# Generated by Django 3.0 on 2024-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0008_assignmentst_stactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='timage',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
