# Generated by Django 3.0 on 2024-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0010_remove_teacherprofile_timage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pf_image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
